### ISSUE TITLE
Repo Files and Folders

### ISSUE THREAD

**Issue by BD103** [BD103/GudHub#2]
A crucial part of Github is being able to view the actual code. If you look at [`app.js`](https://github.com/BD103/GudHub/blob/main/app.js#L18), there is the view `:user/:repo`. I have set up a basic framework for specifying all the files. Give an (alphabetically organized) array that lists all the files in the current folder. I'll add more after I do some research.

**Comment by BD103** [comment]
[Github Rest API](https://docs.github.com/en/rest)

[GraphQL if you're weird](https://docs.github.com/en/graphql)

**Comment by whippingdot** [comment]
Wait what should I do?

Also actually it would be nice if you assign me to every task that you want me to do... I will know what I have to do then.

**Comment by BD103** [comment]
Preferably create a system that will request all the files in a repo through the Github API. Then pass an array of these files into the correct endpoint

**Comment by whippingdot** [comment]
i am unfortunately not good at APIs, that is Rayhan's good point

**Comment by BD103** [comment]
Ah. What would you say is your strong point in web development?

**Comment by whippingdot** [comment]
I am good at HTML, and CSS. And actually I think i am moderate in JavaScript

**Comment by BD103** [comment]
Hm. We're using a CSS framework and Pug, so...
Learn Node? That's what I've been doing on the feat-files branch.

**Comment by whippingdot** [comment]
I am in a node course, but the problem is I am on a NODE course, not express. Express will happen after my node course :(

**Comment by BD103** [comment]
I don't know what to tell you. How do you want to contribute to this project?

**Comment by BD103** [comment]
Ok. Feel free to make the occasional PR! I'll remove you for now, but just ask when you're ready to be added again.

**Comment by whippingdot** [comment]
huh wut? What should I help with in the project (like with HTML and CSS and maybe some JS)

also why are you removing meh?

**Comment by BD103** [comment]
You said you'll be busy. That's perfectly fine.

**Comment by whippingdot** [comment]
oh ok... Add me back next month k

Also ima get discord in like 8 days so tell me your discord ID or whatever then so i can talk to you there

**Comment by BD103** [comment]
Got it
